Iryna kachan lesson 3
eugene-okulik/iryna_kachan pull request #2
Opened 2024-07-08 13:06 UTC by iryna-kachan

2024-07-08 14:44 UTC, eugene-okulik requested changes

2024-07-08 14:44 UTC, eugene-okulik commented on homework/iryna_kachan/homework_3/homework_3_1.py
> +print(a + b) # sum of two numbers
Осталось еще одно. Для всех комментов он просит следовать требованиям PEP-8. Согласно этим требованиям, перед # должно быть 2 пробела, а после # один пробел
```python
print(a + b)  # sum of two numbers
```

2024-07-08 18:14 UTC, iryna-kachan commented on homework/iryna_kachan/homework_3/homework_3_1.py
> +print(a + b) # sum of two numbers
благодарю за подсказку

2024-07-09 06:25 UTC, eugene-okulik approved these changes

2024-07-09 06:25 UTC, merged